language: c
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
sudo: required
services:
 - docker
env:
 - tag="dellelce/nlp-base" BASE="dellelce/uwsgi"
script: docker build -t "${tag}" --build-arg BASE=${BASE} . && ./docker-push.sh "${tag}"
